name: CI

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  Exec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: ".go-version"
          cache-dependency-path: "go.mod"
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a
        with:
          version: v2.13.1
      - run: go install github.com/mfridman/tparse@ba2512e7be150bfcbd6f6220d517d3741f8f2f75
      - run: |
          set -o pipefail
          go test -race -cover -json ./... | tparse --all