name: CI

on:
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  Exec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@v7.0.0
        with:
          go-version-file: ".go-version"
          cache-dependency-path: "go.sum"
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13.1
      - run: go install github.com/mfridman/tparse@v0.18.0
      - run: |
          set -o pipefail
          go test -race -cover -json ./... | tparse --all